language: cpp
matrix:
  include:
  - os: linux
    arch: amd64
    dist: focal
    before_install:
    - sudo apt-get update -qq
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq
#    - sudo apt-get install -y gcc-10 g++-10
#    - ls /usr/bin/g++*
#    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 20
#    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 20
    - sudo apt-get install -y devscripts build-essential lintian dh-make autoconf lua-sql-postgres-dev automake clang liblua5.2-dev libjansson-dev libcurl4-gnutls-dev libiniparser-dev libssl-dev libgd-dev libpng-dev libz3-dev libfreetype6-dev liblua5.1-dev libluajit-5.1-dev libgmp-dev libgtk-3-dev nlohmann-json3-dev
    compiler:
    - clang
#    - gcc
    script:
    - echo $TRAVIS_TAG
    - autoreconf -i 
    - ./configure CC="clang" CXX="clang++"
    - make
    after_script:
     addons:
     artifacts: true

before_install:
    - eval "${MATRIX_EVAL}"



